name: push to zdt

on:
  push:
    branches:
      - gh-pages
    paths:
      - '_site/**'

  workflow_dispatch:

jobs:
  pushzdt:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via rsync action
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude=.git --exclude=.gitignore --exclude=Gemfile* --exclude=*.md
          RSYNC_SOURCE: ./_site/
          #RSYNC_TARGET: ${{ secrets.DEPLOY_PATH }}
          RSYNC_TARGET: ./public_html/dclx
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ZDT_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.ZDT_USER }}
          SSH_HOSTNAME: ${{ secrets.ZDT_HOST }}
          # SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PORT: 22
